fail_fast: false

repos:
  - repo: local
    hooks:
      - id: lab5-black
        name: Lab5 - Black
        entry: python -m black
        args: [Lab5/src]
        pass_filenames: false
        language: system
        always_run: true

      - id: lab5-isort
        name: Lab5 - isort
        entry: python -m isort
        args: [Lab5/src]
        pass_filenames: false
        language: system
        always_run: true

      - id: lab5-pylint
        name: Lab5 - Pylint
        entry: python -m pylint
        args: [Lab5/src]
        pass_filenames: false
        language: system
        always_run: true
      
      - id: lab6-black
        name: Lab6 - Black
        entry: python -m black
        args: [Lab6/src]
        pass_filenames: false
        language: system
        always_run: true

      - id: lab6-isort
        name: Lab6 - isort
        entry: python -m isort
        args: [Lab6/src]
        pass_filenames: false
        language: system
        always_run: true

      - id: lab6-pylint
        name: Lab6 - Pylint
        entry: python -m pylint
        args: [Lab6/src]
        pass_filenames: false
        language: system
        always_run: true
      
      - id: lab7-black
        name: Lab7 - Black
        entry: python -m black
        args: [Lab7/src]
        pass_filenames: false
        language: system
        always_run: true

      - id: lab7-isort
        name: Lab7 - isort
        entry: python -m isort
        args: [Lab7/src]
        pass_filenames: false
        language: system
        always_run: true

      - id: lab7-pylint
        name: Lab7 - Pylint
        entry: python -m pylint
        args: [Lab7/src]
        pass_filenames: false
        language: system
        always_run: true
      
      - id: lab8-black
        name: Lab8 - Black
        entry: python -m black
        args: [Lab8/src]
        pass_filenames: false
        language: system
        always_run: true

      - id: lab8-isort
        name: Lab8 - isort
        entry: python -m isort
        args: [Lab8/src]
        pass_filenames: false
        language: system
        always_run: true

      - id: lab8-pylint
        name: Lab8 - Pylint
        entry: python -m pylint
        args: [Lab8/src]
        pass_filenames: false
        language: system
        always_run: true